### ISSUE TITLE
Need a cancel option

### ISSUE THREAD

**Issue by jdhitsolutions** [smitpi/PSLauncher#1]
I'm not 100% sure how I got here.
![image](https://user-images.githubusercontent.com/12089920/177581882-b32a2703-7259-4699-a224-119fa992a87d.png)

But you should have a Cancel or Exit option to quit without doing anything.

**Comment by smitpi** [comment]
That is a very good point. 

I'll add that in, thanks for the feedback.

**Comment by smitpi** [comment]
Added a quit option.
Thanks for the feedback.

![image](https://user-images.githubusercontent.com/5834660/177687583-2ea0e5da-bfbc-4a6d-adf0-e78334ae8ed7.png)
