### ISSUE TITLE
Don't exit after PowerShell commands

### ISSUE THREAD

**Issue by jdhitsolutions** [smitpi/PSLauncher#3]
I added buttons to run a PowerShell script and a scriptblock. But I can't find a way to keep the PowerShell window open after the code completes so I can see any results.

**Comment by smitpi** [comment]
Hi Jeff,

Added two new buttons. One to start logging and one to stop logging.

Once logging is started, the following applies:
- The main window is visible.
- A Transcript log is created in the temporary folder.
- All PowerShell child windows stay open after execution.

Once logging is disabled, the following applies:
- Main window is hidden.
- The transcript log is opened with default editor.
- All PowerShell child processes are visible (if selected) during execution. And closes after completion.

Let me know what you think, and thanks for the feedback.
